language: go

go:
  - 1.10.x

go_import_path: github.com/chambodn/configmap-microservice-demo

before_install:
  - wget -O - https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
